'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'

import NProgress from "nprogress";
import "nprogress/nprogress.css";

import Router from "next/router";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

NProgress.configure({
  minimum: 0.3,
  easing: "ease",
  speed: 800,
  showSpinner: true,
});

Router.events.on("routeChangeStart", () => NProgress.start());
Router.events.on("routeChangeComplete", () => NProgress.done());
Router.events.on("routeChangeError", () => NProgress.done());

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <div className="absolute bottom-0">GIT LOGO IMG</div>
      </body>
    </html>
  );
}
